// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function map(promise, f) {
  return promise.then(function (v) {
              return Promise.resolve(Curry._1(f, v));
            });
}

function bind(promise, f) {
  return promise.then(Curry.__1(f));
}

function both(promise_a, promise_b) {
  return Promise.all([
              promise_a,
              promise_b
            ]);
}

function $$return(prim) {
  return Promise.resolve(prim);
}

var Open_in_body = {
  $$return: $$return
};

var Open_on_rhs = {
  $$return: $$return
};

var Let_syntax = {
  $$return: $$return,
  bind: bind,
  map: map,
  both: both,
  Open_in_body: Open_in_body,
  Open_on_rhs: Open_on_rhs
};

exports.map = map;
exports.bind = bind;
exports.both = both;
exports.$$return = $$return;
exports.Let_syntax = Let_syntax;
/* No side effect */
